// ============================================================
// API ROUTE: Advanced Analytics
// Purpose: Workflow performance, ROI tracking, cost attribution
// Endpoint: GET /api/analytics
// ============================================================

import { NextRequest, NextResponse } from 'next/server';
import { createSupabaseServerClient, getAuthenticatedUser, getUserWorkspace } from '@/lib/supabase/server';

/**
 * GET /api/analytics
 * Get advanced analytics
 * Query params: ?workflow_id=xxx&period=7d|30d|90d
 */
export async function GET(request: NextRequest) {
  try {
    const user = await getAuthenticatedUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const workspaceData = await getUserWorkspace(user.id);
    if (!workspaceData) return NextResponse.json({ error: 'No workspace found' }, { status: 404 });

    const { searchParams } = new URL(request.url);
    const workflowId = searchParams.get('workflow_id');
    const period = searchParams.get('period') || '30d';

    const supabase = createSupabaseServerClient();
    const workspace = workspaceData.workspace;

    // Calculate date range
    const days = period === '7d' ? 7 : period === '90d' ? 90 : 30;
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - days);

    // Build query
    let runsQuery = supabase
      .from('runs')
      .select('*, workflow:workflows(name, emoji)')
      .eq('workspace_id', workspace.id)
      .gte('created_at', startDate.toISOString())
      .order('created_at', { ascending: false });

    if (workflowId) {
      runsQuery = runsQuery.eq('workflow_id', workflowId);
    }

    const {  runs, error } = await runsQuery;

    if (error) {
      console.error('[GET /api/analytics] Error:', error);
      return NextResponse.json({ error: 'Failed to fetch analytics' }, { status: 500 });
    }

    // Get node-level logs for detailed analysis
    let logsQuery = supabase
      .from('run_logs')
      .select('*, run:runs(workflow_id)')
      .eq('workspace_id', workspace.id)
      .gte('created_at', startDate.toISOString());

    if (workflowId) {
      logsQuery = logsQuery.eq('run.workflow_id', workflowId);
    }

    const {  logs } = await logsQuery;

    // Calculate metrics
    const metrics = calculateMetrics(runs || [], logs || []);

    // Calculate ROI (if we have revenue data)
    const roi = calculateROI(runs || []);

    // Node performance breakdown
    const nodePerformance = calculateNodePerformance(logs || []);

    // Cost attribution by node type
    const costByNodeType = calculateCostByNodeType(logs || []);

    return NextResponse.json({
      period,
      workflow_id: workflowId,
      metrics,
      roi,
      node_performance: nodePerformance,
      cost_by_node_type: costByNodeType,
      time_range: {
        start: startDate.toISOString(),
        end: new Date().toISOString(),
      },
    });
  } catch (err) {
    console.error('[GET /api/analytics] Error:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

/**
 * Calculate overall metrics
 */
function calculateMetrics(runs: any[], logs: any[]) {
  const totalRuns = runs.length;
  const completedRuns = runs.filter(r => r.status === 'completed').length;
  const failedRuns = runs.filter(r => r.status === 'failed').length;

  const totalCost = runs.reduce((sum, r) => sum + (parseFloat(r.total_cost_usd) || 0), 0);
  const enrichmentCost = runs.reduce((sum, r) => sum + (parseFloat(r.enrichment_cost_usd) || 0), 0);
  const aiCost = runs.reduce((sum, r) => sum + (parseFloat(r.ai_cost_usd) || 0), 0);

  const avgDuration = runs.reduce((sum, r) => {
    if (r.started_at && r.completed_at) {
      const duration = new Date(r.completed_at).getTime() - new Date(r.started_at).getTime();
      return sum + duration;
    }
    return sum;
  }, 0) / (completedRuns || 1);

  return {
    total_runs: totalRuns,
    completed_runs: completedRuns,
    failed_runs: failedRuns,
    success_rate: totalRuns > 0 ? (completedRuns / totalRuns) * 100 : 0,
    total_cost: totalCost,
    enrichment_cost: enrichmentCost,
    ai_cost: aiCost,
    avg_cost_per_run: totalRuns > 0 ? totalCost / totalRuns : 0,
    avg_duration_ms: avgDuration,
    total_nodes_executed: logs.length,
    successful_nodes: logs.filter(l => l.status === 'success').length,
    failed_nodes: logs.filter(l => l.status === 'failed').length,
  };
}

/**
 * Calculate ROI (estimated)
 */
function calculateROI(runs: any[]) {
  // This is a simplified ROI calculation
  // In production, you'd track actual revenue generated by each workflow

  const totalCost = runs.reduce((sum, r) => sum + (parseFloat(r.total_cost_usd) || 0), 0);

  // Estimate value based on successful outreach
  // Assume 5% reply rate, $500 avg deal size, 10% close rate
  const estimatedReplies = runs.length * 0.05;
  const estimatedDeals = estimatedReplies * 0.1;
  const estimatedRevenue = estimatedDeals * 500;

  const roi = totalCost > 0 ? ((estimatedRevenue - totalCost) / totalCost) * 100 : 0;

  return {
    estimated_replies: Math.round(estimatedReplies),
    estimated_deals: Math.round(estimatedDeals),
    estimated_revenue: estimatedRevenue,
    total_cost: totalCost,
    roi_percentage: roi,
    cost_per_reply: estimatedReplies > 0 ? totalCost / estimatedReplies : 0,
    cost_per_deal: estimatedDeals > 0 ? totalCost / estimatedDeals : 0,
  };
}

/**
 * Calculate node performance breakdown
 */
function calculateNodePerformance(logs: any[]) {
  const nodeStats = new Map<string, {
    node_type: string;
    total_executions: number;
    successful: number;
    failed: number;
    avg_duration_ms: number;
    total_cost: number;
  }>();

  logs.forEach((log) => {
    const key = `${log.node_type}-${log.node_label || 'Unknown'}`;

    if (!nodeStats.has(key)) {
      nodeStats.set(key, {
        node_type: log.node_type,
        total_executions: 0,
        successful: 0,
        failed: 0,
        avg_duration_ms: 0,
        total_cost: 0,
      });
    }

    const stats = nodeStats.get(key)!;
    stats.total_executions++;
    if (log.status === 'success') stats.successful++;
    if (log.status === 'failed') stats.failed++;
    stats.total_cost += parseFloat(log.cost_usd) || 0;

    if (log.duration_ms) {
      stats.avg_duration_ms = (stats.avg_duration_ms * (stats.total_executions - 1) + log.duration_ms) / stats.total_executions;
    }
  });

  return Array.from(nodeStats.entries()).map(([key, stats]) => ({
    key,
    ...stats,
    success_rate: stats.total_executions > 0 ? (stats.successful / stats.total_executions) * 100 : 0,
  }));
}

/**
 * Calculate cost attribution by node type
 */
function calculateCostByNodeType(logs: any[]) {
  const costByType = new Map<string, number>();

  logs.forEach((log) => {
    const nodeType = log.node_type;
    const cost = parseFloat(log.cost_usd) || 0;

    costByType.set(nodeType, (costByType.get(nodeType) || 0) + cost);
  });

  const totalCost = Array.from(costByType.values()).reduce((sum, cost) => sum + cost, 0);

  return Array.from(costByType.entries()).map(([type, cost]) => ({
    node_type: type,
    cost,
    percentage: totalCost > 0 ? (cost / totalCost) * 100 : 0,
  }));
}
